baseURL = 'https://rikaaa0928.github.io/'
languageCode = 'en-us'
title = 'rikaaa0928 の blog'
theme = 'PaperMod'
[params]
env="production"
[params.profileMode]
enabled = true
title = 'Miracles and Magic Are Charged'
[[params.profileMode.buttons]] 
name = "Blogs"
url = "/posts"
[[params.profileMode.buttons]] 
name = "Github"
url = "https://github.com/rikaaa0928"